### ISSUE TITLE
Install openapi-ruleset package by default

### ISSUE THREAD

**Issue by jamescooke** [jamescooke/openapi-validator-docker#200]
Issue has been opened upstream here: https://github.com/IBM/openapi-validator/issues/354

However, it seems that this can be best fixed by adding

>  the ruleset package as a dependency

## Context

* At image build time a smoke test is run on the image with `docker run` https://github.com/jamescooke/openapi-validator-docker/blob/master/.github/workflows/build_test_tag.yml#L15-L16 , this ensures that the packages are installed as expected.
* This repo tracks the version number of openapi-validator using a GitHub Action (https://github.com/jamescooke/openapi-validator-docker/blob/master/.github/workflows/create_pr_for_release.yml#L23-L28) and opens a PR when a new version is found that does not have a corresponding tag in this repo. However, no tracking of openapi-ruleset versions (e.g. https://github.com/IBM/openapi-validator/releases/tag/%40ibm-cloud%2Fopenapi-ruleset%400.44.0) happens here.

## Expected additions for fix

* An extra step is added to the `build_test_tag` action which replicates the issue in https://github.com/IBM/openapi-validator/issues/354 . This is then run on GHA to show red / failure.
* Extra ruleset package is added as a dependency in `Dockerfile` around (before / after?) the usual install of the validator here: https://github.com/jamescooke/openapi-validator-docker/blob/master/Dockerfile#L6

## Next steps

Probably one or a mixture of:

* A PR is opened to handle the above 🙏🏻 
* Helpful comments are added to this issue showing:
  - A failing case that can be used at build test time.
  - Explanation on whether the ruleset package will need its own tracking

  ... I might then be able to craft the PR myself.

**Comment by dpopp07** [comment]
Thanks for opening this! Replying to [your questions](https://github.com/IBM/openapi-validator/issues/354#issuecomment-1281570363):

> What's the smallest failing test that can be built into the GitHub Actions system to ensure that the ruleset has been installed correctly?

Probably a minimal API definition with a single fault, a minimal `.spectral.yaml` file turning off the rule causing the single fault and extending the ruleset package (`extends: '@ibm-cloud/openapi-ruleset'`)., then running the Docker image with the API definition and config file passed in and ensuring the output is clean.

> Does the docker image build system need to track the version / tag of openapi-ruleset ?

Yes, it will. It wouldn't need to detect when the version is updated though - I think it should just need to install the latest from NPM anytime it installs the latest version of the validator. The ruleset version will never be updated without the validator also being updated in tandem.

**Comment by jamescooke** [comment]
@dpopp07 I've done some experiments in #202 but I can't get the install of `openapi-ruleset` to fix the failing test.

The latest error is here: https://github.com/jamescooke/openapi-validator-docker/actions/runs/3381734773/jobs/5615951098#step:6:5

I've tried a few things to solve this, like installing with `-g` and moving directories.

The issue seems happen because:

* The docker image is built and the ruleset is installed inside `/data`:

  ```sh
  docker run --entrypoint /bin/sh local-image -c ls\ -la
  ```

  ```
  total 100
  drwxr-xr-x    1 root     root          4096 Oct 30 21:08 .
  drwxr-xr-x    1 root     root          4096 Nov  2 23:11 ..
  drwxr-xr-x   83 root     root          4096 Oct 30 21:08 node_modules
  -rw-r--r--    1 root     root         82523 Oct 30 21:08 package-lock.json
  -rw-r--r--    1 root     root            72 Oct 30 21:08 package.json
  ```

* When the new `test` directory containing the `.spectral.yaml` file and the openapi spec file is mounted into `/data` with `--volume "$PWD/test":/data`, then this overwrites the installed node modules and package files:

  ```sh
  docker run --entrypoint /bin/sh --volume "$PWD/test":/data local-image -c ls\ -la
  ```

  ```
  total 16
  drwxrwxr-x    2 node     node          4096 Nov  2 22:58 .
  drwxr-xr-x    1 root     root          4096 Nov  2 23:10 ..
  -rw-rw-r--    1 node     node            64 Nov  2 22:58 .spectral.yaml
  -rw-rw-r--    1 node     node           396 Oct 29 21:43 simple.yaml
  ```

I'm not sure if this problem can be solved with the current docker image setup of using `npm install` to pack the validator inside the image. Any ideas / suggestions?

**Comment by jamescooke** [comment]
Closing because #226
